<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <!-- FONTS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant"> Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<?php if($userSession->isAuthenticated() == false){?>
<nav class="user-interface">
    <ul class="link-list">
        <li><a href="<?= $requestUrl ?>/user" class="button">Créer un compte</a></li>
        <li><a href="<?= $requestUrl ?>/user/login" class="button">Connexion</a></li>
    </ul>
</nav>
    <?php } else {?>
<nav class="user-interface">
    <ul class="link-list">
        <li><a href="<?= $requestUrl ?>/booking" class="button">Réserver</a></li>
        <li><a href="<?= $requestUrl ?>/order" class="button">Commander</a></li>
        <li><span>Bonjour <?= $userSession->getFullName()?> </span></li>
        <li><a href="<?= $requestUrl ?>/user/logout" class="button" id="logout">Déconnexion</a></li>
    </ul>
</nav>
<?php } ?>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>